//Auth actions
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILED = "REGISTER_FAILED";
export const CHANGE_SETTINGS = "CHANGE_SETTINGS";

//Users actions
export const GET_FOLLOWERS = "GET_FOLLOWERS";
export const GET_FOLLOWING = "GET_FOLLOWING";
export const GETTING_ALL_USERS = "GETTING_ALL_USERS";
export const GET_ALL_USERS = "GET_ALL_USERS";
export const GET_ALL_USERS_ERROR = "GET_ALL_USERS_ERROR";
export const UPDATING_FOLLOW = "UPDATING_FOLLOW";
export const ADD_FOLLOWERS = "ADD_FOLLOWERS";
export const ADD_FOLLOWING = "ADD_FOLLOWING";
export const REMOVE_FOLLOWERS = "REMOVE_FOLLOWERS";
export const REMOVE_FOLLOWING = "REMOVE_FOLLOWING";
export const UPDATE_FOLLOW_ERROR = "UPDATE_FOLLOW_ERROR";

//Errors actions
export const RETURN_ERRORS = "RETURN_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

//Posts actions
export const CREATE_POST = "CREATE_POST";
export const CREATING_POST = "CREATING_POST";
export const CREATE_POST_FAILED = "CREATE_POST_FAILED";
export const GET_POSTS = "GET_POSTS";
export const GETTING_POSTS = "GETTING_POSTS";
export const GET_POSTS_FAILED = "GET_POSTS_FAILED";
export const ADD_COMMENT = "ADD_COMMENT";
export const DELETE_COMMENT = "DELETE_COMMENT";
export const DELETE_POST = "DELETE_POST";
export const UPDATING_POST_LIKE = "UPDATING_POST_LIKE";
export const UPDATE_POST_LIKES = "UPDATE_POST_LIKES";
